name: nuke
description: Super slim state management that gets the job done.
version: 0.0.4
homepage: https://github.com/1N50MN14
repository: https://github.com/1N50MN14/nuke


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_to_regexp: ^0.3.0
  uuid: ^2.0.4
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
